
version: '3'
services:
    authserver:
      image: brighthive/authserver:latest
      depends_on:
        - postgres
      environment:
        - APP_ENV=DEVELOPMENT
        - PG_USER=brighthive_admin
        - PG_PASSWORD=password
        - PG_HOSTNAME=postgres
        - PG_DB=authserver
      ports:
        - "8000:8000"
      volumes:
        - ../:/authserver
      stdin_open: true
      tty: true
    postgres:
      image: postgres:11.2
      environment:
        - POSTGRES_USER=brighthive_admin
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=authserver
      ports:
        - "5432:5432"